'use client';

import { useEffect, useMemo, useState } from 'react';
import { FileUp, ImagePlus, Plus, Trash2 } from 'lucide-react';
import { AuthGuard } from '@/components/auth-guard';
import { AdminShell } from '@/components/admin-shell';
import { Modal, PageHeader, Skeleton } from '@/components/ui';
import { useSession } from '@/contexts/session-context';
import { getExamApi, type AdminQuestionInput, type ExamRecord, type QuestionRecord } from '@/lib/api';

const empty = (examId = ''): AdminQuestionInput => ({ examId, questionText: '', optionA: '', optionB: '', optionC: '', optionD: '', correctAnswer: 'A', score: 1, difficulty: 'Sedang', tag: '', status: 'ACTIVE' });

export default function QuestionsPage() {
  const { session } = useSession();
  const [items, setItems] = useState<QuestionRecord[]>([]); const [exams, setExams] = useState<ExamRecord[]>([]); const [examFilter, setExamFilter] = useState(''); const [loading, setLoading] = useState(true); const [open, setOpen] = useState(false); const [importOpen, setImportOpen] = useState(false); const [form, setForm] = useState<AdminQuestionInput>(empty()); const [csv, setCsv] = useState(''); const [message, setMessage] = useState(''); const [uploading, setUploading] = useState(false);
  const load = async () => { if (!session) return; const [q,e] = await Promise.all([getExamApi().listQuestions(session.token, examFilter || undefined), getExamApi().listExams(session.token)]); setItems(q); setExams(e); setLoading(false); };
  useEffect(() => { load(); }, [session, examFilter]);
  const filtered = useMemo(() => items, [items]);
  const save = async (e: React.FormEvent) => { e.preventDefault(); if (!session) return; await getExamApi().saveQuestion(session.token, form); setOpen(false); setForm(empty(examFilter)); load(); };
  const uploadImage = async (file?: File) => { if (!file || !session) return; if (file.size > 2_500_000) { setMessage('Gambar maksimal 2,5 MB sebelum optimasi.'); return; } setUploading(true); try { const base64 = await new Promise<string>((resolve,reject)=>{ const reader = new FileReader(); reader.onload=()=>resolve(String(reader.result).split(',')[1] || ''); reader.onerror=()=>reject(reader.error); reader.readAsDataURL(file); }); const uploaded = await getExamApi().uploadQuestionImage(session.token, { name:file.name,mimeType:file.type || 'image/jpeg',base64 }); setForm((f)=>({...f,imageFileId:uploaded.fileId})); setMessage(`Gambar tersimpan: ${uploaded.name}`); } finally { setUploading(false); } };
  const remove = async (id:string)=>{ if(!session || !confirm('Hapus soal ini?')) return; await getExamApi().deleteQuestion(session.token,id); load(); };
  const importCsv = async()=>{ if(!session) return; const result=await getExamApi().importQuestionsCsv(session.token,csv); setMessage(`${result.imported} soal diimpor.${result.errors.length ? ` ${result.errors.length} baris bermasalah.`:''}`); setImportOpen(false); load(); };
  return <AuthGuard role="teacher"><AdminShell><PageHeader eyebrow="BANK SOAL" title="Pertanyaan" description="Kunci jawaban tetap berada di backend dan tidak dikirim ke perangkat siswa." action={<div className="action-row"><button className="button secondary" onClick={()=>setImportOpen(true)}><FileUp size={18}/>Impor CSV</button><button className="button primary" onClick={()=>{setForm(empty(examFilter || exams[0]?.examId));setOpen(true)}}><Plus size={18}/>Tambah soal</button></div>}/>
    {message && <div className="notice neutral">{message}</div>}<div className="toolbar"><select value={examFilter} onChange={(e)=>setExamFilter(e.target.value)}><option value="">Semua ujian</option>{exams.map(e=><option key={e.examId} value={e.examId}>{e.title}</option>)}</select></div>
    {loading ? <Skeleton height={300}/> : <section className="panel"><div className="table-wrap"><table><thead><tr><th>Soal</th><th>Ujian</th><th>Kunci</th><th>Bobot</th><th></th></tr></thead><tbody>{filtered.map((q)=><tr key={q.questionId}><td className="question-cell"><strong>{q.questionText}</strong><small>{q.difficulty} • {q.tag || 'Tanpa tag'}{q.imageFileId ? ' • Ada gambar' : ''}</small></td><td>{exams.find(e=>e.examId===q.examId)?.title || q.examId}</td><td><span className="key-pill">{q.correctAnswer || '—'}</span></td><td>{q.score || 1}</td><td><div className="row-actions"><button onClick={()=>{setForm({...q,correctAnswer:q.correctAnswer || 'A',score:q.score || 1});setOpen(true)}}>Edit</button><button className="danger" onClick={()=>remove(q.questionId)}><Trash2/></button></div></td></tr>)}</tbody></table></div></section>}
    <Modal open={open} onClose={()=>setOpen(false)} title={form.questionId?'Edit soal':'Tambah soal'} size="large"><form className="form-grid" onSubmit={save}><label className="span-2">Ujian<select required value={form.examId} onChange={(e)=>setForm({...form,examId:e.target.value})}><option value="">Pilih ujian</option>{exams.map(e=><option key={e.examId} value={e.examId}>{e.title}</option>)}</select></label><label className="span-2">Pertanyaan<textarea required rows={4} value={form.questionText} onChange={(e)=>setForm({...form,questionText:e.target.value})}/></label>{(['A','B','C','D'] as const).map(key=><label key={key}>Pilihan {key}<input required value={form[`option${key}`]} onChange={(e)=>setForm({...form,[`option${key}`]:e.target.value})}/></label>)}<label>Kunci jawaban<select value={form.correctAnswer} onChange={(e)=>setForm({...form,correctAnswer:e.target.value})}><option>A</option><option>B</option><option>C</option><option>D</option></select></label><label>Bobot<input type="number" min="0.1" step="0.1" value={form.score} onChange={(e)=>setForm({...form,score:Number(e.target.value)})}/></label><label>Kesulitan<select value={form.difficulty} onChange={(e)=>setForm({...form,difficulty:e.target.value})}><option>Mudah</option><option>Sedang</option><option>Sulit</option></select></label><label>Tag<input value={form.tag} onChange={(e)=>setForm({...form,tag:e.target.value})}/></label><label className="span-2 upload-box"><span><ImagePlus/>Gambar soal opsional</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e)=>uploadImage(e.target.files?.[0])}/><small>{uploading?'Mengunggah...':form.imageFileId?`File ID: ${form.imageFileId}`:'Disarankan WebP/JPEG teroptimasi 100–300 KB.'}</small></label><div className="form-actions span-2"><button type="button" className="button secondary" onClick={()=>setOpen(false)}>Batal</button><button className="button primary">Simpan soal</button></div></form></Modal>
    <Modal open={importOpen} onClose={()=>setImportOpen(false)} title="Impor soal CSV"><p className="modal-help">Gunakan header: examId,questionText,optionA,optionB,optionC,optionD,correctAnswer,score,difficulty,tag</p><textarea className="csv-area" rows={10} value={csv} onChange={(e)=>setCsv(e.target.value)} placeholder="Tempel isi CSV di sini..."/><button className="button primary full" onClick={importCsv}>Validasi & impor</button></Modal>
  </AdminShell></AuthGuard>;
}
