'use client';

import { useEffect, useMemo, useState } from 'react';
import { Copy, Edit3, Plus, Trash2 } from 'lucide-react';
import { AuthGuard } from '@/components/auth-guard';
import { AdminShell } from '@/components/admin-shell';
import { Badge, Modal, PageHeader, Skeleton } from '@/components/ui';
import { useSession } from '@/contexts/session-context';
import { getExamApi, type AdminExamInput, type ExamRecord } from '@/lib/api';
import { formatDateTime } from '@/lib/format';

const emptyForm = (): AdminExamInput => ({
  title: '', subject: '', className: 'XI IPA 1', startTime: new Date(Date.now() + 3600_000).toISOString().slice(0,16), endTime: new Date(Date.now() + 25 * 3600_000).toISOString().slice(0,16), durationMinutes: 45, questionCount: 20, status: 'DRAFT', randomizeQuestion: true, randomizeOption: true, resultVisibility: 'immediate', token: '', attemptPolicy: 'single', instructions: 'Kerjakan secara mandiri dan pastikan jawaban telah tersimpan sebelum mengumpulkan.'
});

export default function ExamsPage() {
  const { session } = useSession(); const [items, setItems] = useState<ExamRecord[]>([]); const [loading, setLoading] = useState(true); const [open, setOpen] = useState(false); const [form, setForm] = useState<AdminExamInput>(emptyForm()); const [saving, setSaving] = useState(false); const [query, setQuery] = useState('');
  const load = () => session && getExamApi().listExams(session.token).then(setItems).finally(() => setLoading(false));
  useEffect(() => { load(); }, [session]);
  const filtered = useMemo(() => items.filter((e) => `${e.title} ${e.subject} ${e.className}`.toLowerCase().includes(query.toLowerCase())), [items, query]);
  const edit = (exam: ExamRecord) => { setForm({ ...exam, startTime: new Date(exam.startTime).toISOString().slice(0,16), endTime: new Date(exam.endTime).toISOString().slice(0,16), token: exam.token || '' }); setOpen(true); };
  const save = async (e: React.FormEvent) => { e.preventDefault(); if (!session) return; setSaving(true); try { await getExamApi().saveExam(session.token, { ...form, startTime: new Date(form.startTime).toISOString(), endTime: new Date(form.endTime).toISOString() }); setOpen(false); setForm(emptyForm()); await load(); } finally { setSaving(false); } };
  const remove = async (id: string) => { if (!session || !confirm('Hapus ujian ini?')) return; await getExamApi().deleteExam(session.token, id); load(); };
  const duplicate = async (id: string) => { if (!session) return; await getExamApi().duplicateExam(session.token, id); load(); };
  return <AuthGuard role="teacher"><AdminShell><PageHeader eyebrow="MANAJEMEN" title="Ujian" description="Atur jadwal, durasi, token, randomisasi, dan visibilitas hasil." action={<button className="button primary" onClick={() => { setForm(emptyForm()); setOpen(true); }}><Plus size={18}/>Buat ujian</button>}/><div className="toolbar"><input className="search-input" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Cari ujian..."/></div>{loading ? <Skeleton height={280}/> : <section className="panel"><div className="table-wrap"><table><thead><tr><th>Ujian</th><th>Kelas</th><th>Durasi</th><th>Status</th><th>Jadwal</th><th></th></tr></thead><tbody>{filtered.map((exam) => <tr key={exam.examId}><td><strong>{exam.title}</strong><small>{exam.subject} • {exam.questionCount} soal</small></td><td>{exam.className}</td><td>{exam.durationMinutes} menit</td><td><Badge tone={exam.status === 'ACTIVE' ? 'success' : exam.status === 'DRAFT' ? 'neutral' : 'primary'}>{exam.status}</Badge></td><td><small>{formatDateTime(exam.startTime)}<br/>s.d. {formatDateTime(exam.endTime)}</small></td><td><div className="row-actions"><button onClick={() => edit(exam)} title="Edit"><Edit3/></button><button onClick={() => duplicate(exam.examId)} title="Duplikat"><Copy/></button><button className="danger" onClick={() => remove(exam.examId)} title="Hapus"><Trash2/></button></div></td></tr>)}</tbody></table></div></section>}
  <Modal open={open} onClose={() => setOpen(false)} title={form.examId ? 'Edit ujian' : 'Buat ujian'} size="large"><form className="form-grid" onSubmit={save}><label className="span-2">Nama ujian<input required value={form.title} onChange={(e) => setForm({...form,title:e.target.value})}/></label><label>Mata pelajaran<input required value={form.subject} onChange={(e) => setForm({...form,subject:e.target.value})}/></label><label>Kelas<input required value={form.className} onChange={(e) => setForm({...form,className:e.target.value})}/></label><label>Mulai<input type="datetime-local" required value={form.startTime} onChange={(e) => setForm({...form,startTime:e.target.value})}/></label><label>Selesai<input type="datetime-local" required value={form.endTime} onChange={(e) => setForm({...form,endTime:e.target.value})}/></label><label>Durasi (menit)<input type="number" min="1" value={form.durationMinutes} onChange={(e) => setForm({...form,durationMinutes:Number(e.target.value)})}/></label><label>Jumlah soal<input type="number" min="1" value={form.questionCount} onChange={(e) => setForm({...form,questionCount:Number(e.target.value)})}/></label><label>Status<select value={form.status} onChange={(e) => setForm({...form,status:e.target.value as AdminExamInput['status']})}><option>DRAFT</option><option>PUBLISHED</option><option>ACTIVE</option><option>CLOSED</option></select></label><label>Visibilitas hasil<select value={form.resultVisibility} onChange={(e) => setForm({...form,resultVisibility:e.target.value as AdminExamInput['resultVisibility']})}><option value="immediate">Langsung</option><option value="after_exam_closed">Setelah ujian ditutup</option><option value="manual_publish">Manual</option><option value="hidden">Disembunyikan</option></select></label><label className="span-2">Token ujian (opsional)<input value={form.token || ''} onChange={(e) => setForm({...form,token:e.target.value.toUpperCase()})}/></label><label className="check-label"><input type="checkbox" checked={form.randomizeQuestion} onChange={(e) => setForm({...form,randomizeQuestion:e.target.checked})}/>Acak urutan soal</label><label className="check-label"><input type="checkbox" checked={form.randomizeOption} onChange={(e) => setForm({...form,randomizeOption:e.target.checked})}/>Acak pilihan jawaban</label><label className="span-2">Petunjuk<textarea rows={3} value={form.instructions} onChange={(e) => setForm({...form,instructions:e.target.value})}/></label><div className="form-actions span-2"><button type="button" className="button secondary" onClick={() => setOpen(false)}>Batal</button><button className="button primary" disabled={saving}>{saving ? 'Menyimpan...' : 'Simpan ujian'}</button></div></form></Modal>
  </AdminShell></AuthGuard>;
}
