function getDashboardStats_(payload){
  const ctx=requireManager_(payload.token),now=Date.now(),exams=visibleExamsFor_(ctx),examIds={};exams.forEach(e=>examIds[String(e.examId)]=true);
  const attempts=rows_('ATTEMPTS').filter(a=>examIds[String(a.examId)]),students=rows_('USERS').filter(u=>String(u.role)==='student'&&String(u.status)==='ACTIVE');
  return{activeExams:exams.filter(e=>new Date(e.startTime).getTime()<=now&&new Date(e.endTime).getTime()>=now&&['PUBLISHED','ACTIVE'].indexOf(String(e.status))>=0).length,upcomingExams:exams.filter(e=>new Date(e.startTime).getTime()>now&&['PUBLISHED','ACTIVE'].indexOf(String(e.status))>=0).length,students:students.length,inProgress:attempts.filter(a=>String(a.status)==='IN_PROGRESS').length,submitted:attempts.filter(a=>String(a.status)==='SUBMITTED').length,notSubmitted:Math.max(0,students.length-attempts.filter(a=>String(a.status)==='SUBMITTED').length)};
}
function listExams_(payload){const ctx=requireManager_(payload.token);return visibleExamsFor_(ctx).map(normalizeExamRecord_);}
function normalizeExamRecord_(r){const owner=findRowByKey_('USERS','userId',r.ownerId);return Object.assign(normalizeExam_(r),{token:String(r.token||''),instructions:String(r.instructions||''),ownerId:String(r.ownerId||''),ownerName:owner?String(owner.name):''});}
function saveExam_(payload){
  const ctx=requireManager_(payload.token),input=payload.input||{};if(!input.title||!input.subject||!input.className)throw apiError_('Nama ujian, mata pelajaran, dan kelas wajib diisi.','BAD_REQUEST');
  const id=String(input.examId||uid_('EX')),existing=findRowByKey_('EXAMS','examId',id);if(existing)assertManageExam_(ctx,existing);
  let ownerId=String(ctx.user.role)==='teacher'?String(ctx.user.userId):String(input.ownerId||(existing&&existing.ownerId)||'');
  if(!ownerId)throw apiError_('Pilih guru pemilik ujian.','BAD_REQUEST');const owner=findRowByKey_('USERS','userId',ownerId);if(!owner||String(owner.role)!=='teacher'||String(owner.status)!=='ACTIVE')throw apiError_('Guru pemilik ujian tidak valid.','BAD_REQUEST');
  const now=nowIso_(),obj={examId:id,ownerId,title:String(input.title),subject:String(input.subject),className:String(input.className),startTime:new Date(input.startTime).toISOString(),endTime:new Date(input.endTime).toISOString(),durationMinutes:Number(input.durationMinutes||45),questionCount:Number(input.questionCount||1),status:String(input.status||'DRAFT'),randomizeQuestion:asBool_(input.randomizeQuestion),randomizeOption:asBool_(input.randomizeOption),resultVisibility:String(input.resultVisibility||'hidden'),token:String(input.token||''),attemptPolicy:String(input.attemptPolicy||'single'),instructions:String(input.instructions||''),createdAt:existing?existing.createdAt:now,updatedAt:now};
  if(existing)updateRowByKey_('EXAMS','examId',id,obj);else appendObject_('EXAMS',obj);try{CacheService.getScriptCache().remove('exam:'+id)}catch(_){}audit_(ctx.user.userId,'SAVE_EXAM',id,{ownerId});return normalizeExamRecord_(findRowByKey_('EXAMS','examId',id));
}
function deleteExam_(payload){const ctx=requireManager_(payload.token),id=String(payload.examId||''),exam=findRowByKey_('EXAMS','examId',id);assertManageExam_(ctx,exam);if(rows_('ATTEMPTS').some(a=>String(a.examId)===id))throw apiError_('Ujian sudah memiliki attempt dan tidak boleh dihapus. Tutup ujian sebagai gantinya.','EXAM_IN_USE');deleteRowByKey_('EXAMS','examId',id);audit_(ctx.user.userId,'DELETE_EXAM',id,{});return null;}
function duplicateExam_(payload){const ctx=requireManager_(payload.token),src=findRowByKey_('EXAMS','examId',payload.examId);assertManageExam_(ctx,src);const newId=uid_('EX'),now=nowIso_(),copy={};SM.SHEETS.EXAMS.forEach(h=>copy[h]=src[h]);copy.examId=newId;copy.ownerId=String(ctx.user.role)==='teacher'?ctx.user.userId:src.ownerId;copy.title=String(src.title)+' (Salinan)';copy.status='DRAFT';copy.createdAt=now;copy.updatedAt=now;appendObject_('EXAMS',copy);const map={},questions=rows_('QUESTIONS').filter(q=>String(q.examId)===String(src.examId));questions.forEach(q=>{const newQ=uid_('Q');map[String(q.questionId)]=newQ;appendObject_('QUESTIONS',{questionId:newQ,examId:newId,questionText:q.questionText,optionA:q.optionA,optionB:q.optionB,optionC:q.optionC,optionD:q.optionD,imageFileId:q.imageFileId||'',questionType:q.questionType||'MULTIPLE_CHOICE',difficulty:q.difficulty||'Sedang',tag:q.tag||'',status:q.status||'ACTIVE',createdAt:now,updatedAt:now});});const keys=rows_('ANSWER_KEYS');Object.keys(map).forEach(oldId=>{const k=keys.find(x=>String(x.questionId)===oldId);if(k)appendObject_('ANSWER_KEYS',{questionId:map[oldId],correctAnswer:k.correctAnswer,score:k.score});});audit_(ctx.user.userId,'DUPLICATE_EXAM',newId,{source:src.examId});return normalizeExamRecord_(findRowByKey_('EXAMS','examId',newId));}
function listQuestions_(payload){const ctx=requireManager_(payload.token),allowed={};visibleExamsFor_(ctx).forEach(e=>allowed[String(e.examId)]=true);const keys=rows_('ANSWER_KEYS');return rows_('QUESTIONS').filter(q=>allowed[String(q.examId)]&&(!payload.examId||String(q.examId)===String(payload.examId))).map(q=>{const k=keys.find(x=>String(x.questionId)===String(q.questionId));return{questionId:String(q.questionId),examId:String(q.examId),questionText:String(q.questionText),optionA:String(q.optionA),optionB:String(q.optionB),optionC:String(q.optionC),optionD:String(q.optionD),correctAnswer:k?String(k.correctAnswer):'',score:k?Number(k.score||1):1,imageFileId:String(q.imageFileId||''),imageUrl:q.imageFileId?drivePublicUrl_(String(q.imageFileId)):'',difficulty:String(q.difficulty||'Sedang'),tag:String(q.tag||''),status:String(q.status||'ACTIVE')}});}
function saveQuestion_(payload){const ctx=requireManager_(payload.token),input=payload.input||{},exam=findRowByKey_('EXAMS','examId',input.examId);assertManageExam_(ctx,exam);if(!input.questionText||!input.optionA||!input.optionB||!input.optionC||!input.optionD)throw apiError_('Soal dan empat pilihan wajib diisi.','BAD_REQUEST');if(['A','B','C','D'].indexOf(String(input.correctAnswer))<0)throw apiError_('Kunci jawaban harus A/B/C/D.','BAD_REQUEST');const id=String(input.questionId||uid_('Q')),now=nowIso_(),obj={questionId:id,examId:String(input.examId),questionText:String(input.questionText),optionA:String(input.optionA),optionB:String(input.optionB),optionC:String(input.optionC),optionD:String(input.optionD),imageFileId:String(input.imageFileId||''),questionType:'MULTIPLE_CHOICE',difficulty:String(input.difficulty||'Sedang'),tag:String(input.tag||''),status:String(input.status||'ACTIVE'),createdAt:now,updatedAt:now},existing=findRowByKey_('QUESTIONS','questionId',id);if(existing){const oldExam=findRowByKey_('EXAMS','examId',existing.examId);assertManageExam_(ctx,oldExam);obj.createdAt=existing.createdAt||now;updateRowByKey_('QUESTIONS','questionId',id,obj)}else appendObject_('QUESTIONS',obj);const key=findRowByKey_('ANSWER_KEYS','questionId',id),keyObj={questionId:id,correctAnswer:String(input.correctAnswer),score:Number(input.score||1)};if(key)updateRowByKey_('ANSWER_KEYS','questionId',id,keyObj);else appendObject_('ANSWER_KEYS',keyObj);audit_(ctx.user.userId,'SAVE_QUESTION',id,{examId:input.examId});return listQuestions_({token:payload.token,examId:input.examId}).find(q=>q.questionId===id);}
function deleteQuestion_(payload){const ctx=requireManager_(payload.token),q=findRowByKey_('QUESTIONS','questionId',payload.questionId);if(!q)throw apiError_('Soal tidak ditemukan.','NOT_FOUND');assertManageExam_(ctx,findRowByKey_('EXAMS','examId',q.examId));deleteRowByKey_('QUESTIONS','questionId',payload.questionId);deleteRowByKey_('ANSWER_KEYS','questionId',payload.questionId);audit_(ctx.user.userId,'DELETE_QUESTION',payload.questionId,{});return null;}
function importQuestionsCsv_(payload){const ctx=requireManager_(payload.token),text=String(payload.csvText||'').trim();if(!text)return{imported:0,errors:['CSV kosong.']};const lines=text.split(/\r?\n/),headers=parseCsvLine_(lines.shift()).map(h=>h.trim()),errors=[];let imported=0;for(let i=0;i<lines.length;i++){if(!lines[i].trim())continue;const values=parseCsvLine_(lines[i]),row={};headers.forEach((h,j)=>row[h]=values[j]||'');try{const exam=findRowByKey_('EXAMS','examId',row.examId);assertManageExam_(ctx,exam);saveQuestion_({token:payload.token,input:{examId:row.examId,questionText:row.questionText,optionA:row.optionA,optionB:row.optionB,optionC:row.optionC,optionD:row.optionD,correctAnswer:row.correctAnswer,score:Number(row.score||1),difficulty:row.difficulty||'Sedang',tag:row.tag||'',status:'ACTIVE'}});imported++}catch(e){errors.push('Baris '+(i+2)+': '+e.message)}}audit_(ctx.user.userId,'IMPORT_QUESTIONS','',{imported,errors:errors.length});return{imported,errors};}
function parseCsvLine_(line){const out=[];let cur='',quoted=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(quoted&&line[i+1]==='"'){cur+='"';i++}else quoted=!quoted}else if(ch===','&&!quoted){out.push(cur);cur=''}else cur+=ch}out.push(cur);return out;}
function listStudents_(payload){requireManager_(payload.token);return rows_('USERS').filter(u=>String(u.role)==='student').map(sanitizeUser_);}
function saveStudent_(payload){const ctx=requireManager_(payload.token),input=payload.input||{},id=String(input.userId||uid_('S')),now=nowIso_();if(!input.name||!input.username||!input.className)throw apiError_('Nama, username, dan kelas wajib diisi.','BAD_REQUEST');const duplicate=rows_('USERS').find(u=>String(u.username).toLowerCase()===String(input.username).toLowerCase()&&String(u.userId)!==id);if(duplicate)throw apiError_('Username sudah digunakan.','DUPLICATE_USERNAME');const existing=findRowByKey_('USERS','userId',id);if(existing&&String(existing.role)!=='student')throw apiError_('Akun bukan siswa.','BAD_REQUEST');const salt=existing?String(existing.passwordSalt):Utilities.getUuid(),passwordHash=input.password?hashPassword_(input.password,salt):(existing?existing.passwordHash:'');if(!passwordHash)throw apiError_('Password wajib untuk peserta baru.','BAD_REQUEST');const obj={userId:id,name:String(input.name),className:String(input.className),subject:'',username:String(input.username),passwordHash,passwordSalt:salt,role:'student',status:String(input.status||'ACTIVE'),createdAt:existing?existing.createdAt:now,updatedAt:now};if(existing)updateRowByKey_('USERS','userId',id,obj);else appendObject_('USERS',obj);audit_(ctx.user.userId,'SAVE_STUDENT',id,{});return sanitizeUser_(findRowByKey_('USERS','userId',id));}
function deleteStudent_(payload){const ctx=requireManager_(payload.token),user=findRowByKey_('USERS','userId',payload.userId);if(!user||String(user.role)!=='student')throw apiError_('Siswa tidak ditemukan.','NOT_FOUND');const used=rows_('ATTEMPTS').some(a=>String(a.studentId)===String(payload.userId));if(used)updateRowByKey_('USERS','userId',payload.userId,{status:'INACTIVE',updatedAt:nowIso_()});else deleteRowByKey_('USERS','userId',payload.userId);audit_(ctx.user.userId,'DELETE_STUDENT',payload.userId,{softDelete:used});return null;}
function listTeachers_(payload){requireSuperAdmin_(payload.token);return rows_('USERS').filter(u=>String(u.role)==='teacher').map(sanitizeUser_);}
function saveTeacher_(payload){const ctx=requireSuperAdmin_(payload.token),input=payload.input||{},id=String(input.userId||uid_('T')),now=nowIso_();if(!input.name||!input.username||!input.subject)throw apiError_('Nama, username, dan mata pelajaran wajib diisi.','BAD_REQUEST');const duplicate=rows_('USERS').find(u=>String(u.username).toLowerCase()===String(input.username).toLowerCase()&&String(u.userId)!==id);if(duplicate)throw apiError_('Username sudah digunakan.','DUPLICATE_USERNAME');const existing=findRowByKey_('USERS','userId',id);if(existing&&String(existing.role)!=='teacher')throw apiError_('Akun bukan guru.','BAD_REQUEST');const salt=existing?String(existing.passwordSalt):Utilities.getUuid(),passwordHash=input.password?hashPassword_(input.password,salt):(existing?existing.passwordHash:'');if(!passwordHash)throw apiError_('Password wajib untuk guru baru.','BAD_REQUEST');const obj={userId:id,name:String(input.name),className:'',subject:String(input.subject),username:String(input.username),passwordHash,passwordSalt:salt,role:'teacher',status:String(input.status||'ACTIVE'),createdAt:existing?existing.createdAt:now,updatedAt:now};if(existing)updateRowByKey_('USERS','userId',id,obj);else appendObject_('USERS',obj);audit_(ctx.user.userId,'SAVE_TEACHER',id,{});return sanitizeUser_(findRowByKey_('USERS','userId',id));}
function deleteTeacher_(payload){const ctx=requireSuperAdmin_(payload.token),id=String(payload.userId||''),user=findRowByKey_('USERS','userId',id);if(!user||String(user.role)!=='teacher')throw apiError_('Guru tidak ditemukan.','NOT_FOUND');if(rows_('EXAMS').some(e=>String(e.ownerId)===id))throw apiError_('Guru masih memiliki ujian. Pindahkan atau hapus ujian terlebih dahulu.','TEACHER_IN_USE');deleteRowByKey_('USERS','userId',id);audit_(ctx.user.userId,'DELETE_TEACHER',id,{});return null;}
function getMonitoring_(payload){const ctx=requireManager_(payload.token),allowed={};visibleExamsFor_(ctx).forEach(e=>allowed[String(e.examId)]=true);const users=rows_('USERS'),exams=rows_('EXAMS');return rows_('ATTEMPTS').filter(a=>allowed[String(a.examId)]&&(!payload.examId||String(a.examId)===String(payload.examId))).map(a=>{const u=users.find(x=>String(x.userId)===String(a.studentId))||{},e=exams.find(x=>String(x.examId)===String(a.examId))||{};return{attemptId:String(a.attemptId),studentId:String(a.studentId),studentName:String(u.name||a.studentId),className:String(u.className||''),examId:String(a.examId),examTitle:String(e.title||a.examId),status:String(a.status),startedAt:a.startedAt?new Date(a.startedAt).toISOString():'',lastSyncAt:a.lastSyncAt?new Date(a.lastSyncAt).toISOString():'',revision:Number(a.revision||0),submittedAt:a.submittedAt?new Date(a.submittedAt).toISOString():undefined};});}
function getAdminResults_(payload){const ctx=requireManager_(payload.token),allowed={};visibleExamsFor_(ctx).forEach(e=>allowed[String(e.examId)]=true);const users=rows_('USERS'),exams=rows_('EXAMS');return rows_('SUBMISSIONS').filter(s=>allowed[String(s.examId)]&&(!payload.examId||String(s.examId)===String(payload.examId))).map(s=>{const u=users.find(x=>String(x.userId)===String(s.studentId))||{},e=exams.find(x=>String(x.examId)===String(s.examId))||{};return{submissionId:String(s.submissionId),attemptId:String(s.attemptId),studentId:String(s.studentId),studentName:String(u.name||s.studentId),className:String(u.className||''),examId:String(s.examId),examTitle:String(e.title||s.examId),score:Number(s.score||0),correctCount:Number(s.correctCount||0),wrongCount:Number(s.wrongCount||0),blankCount:Number(s.blankCount||0),submittedAt:new Date(s.submittedAt).toISOString()};});}
