function setupSainsMasemba(){
  const props=PropertiesService.getScriptProperties();let spreadsheetId=props.getProperty('SPREADSHEET_ID'),ss;
  if(spreadsheetId){ss=SpreadsheetApp.openById(spreadsheetId)}else{ss=SpreadsheetApp.create('SainsMasemba Database');spreadsheetId=ss.getId();props.setProperty('SPREADSHEET_ID',spreadsheetId)}
  Object.keys(SM.SHEETS).forEach(name=>ensureSheet_(ss,name,SM.SHEETS[name]));
  let folderId=props.getProperty('DRIVE_FOLDER_ID');if(!folderId){const folder=DriveApp.createFolder('SainsMasemba Question Images');folderId=folder.getId();props.setProperty('DRIVE_FOLDER_ID',folderId)}
  props.setProperty('PUBLIC_QUESTION_IMAGES','true');getPepper_();
  migrateLegacyRoles_();
  const superPassword=ensureUser_({userId:'SA-001',name:'Super Admin SainsMasemba',username:'superadmin',className:'',subject:'',role:'super_admin',password:'super123'});
  const teacherPassword=ensureUser_({userId:'T-001',name:'Guru Fisika SainsMasemba',username:'guru',className:'',subject:'Fisika',role:'teacher',password:'guru123'});
  ensureUser_({userId:'S-001',name:'Siswa Demo',username:'siswa',className:'XI IPA 1',subject:'',role:'student',password:'siswa123'});
  migrateExamOwners_('T-001');
  if(!findRowByKey_('EXAMS','examId','EX-DEMO-001'))seedDemoExam_();
  const result={spreadsheetId,spreadsheetUrl:ss.getUrl(),driveFolderId:folderId,demoAccounts:{superAdmin:{username:'superadmin',password:'super123'},teacher:{username:'guru',password:'guru123'},student:{username:'siswa',password:'siswa123'}}};
  console.log(JSON.stringify(result,null,2));return result;
}
function ensureUser_(input){const existing=findRowByKey_('USERS','username',input.username);if(existing){if(String(existing.role)!==String(input.role))updateRowByKey_('USERS','userId',existing.userId,{role:input.role,subject:input.subject||existing.subject||'',className:input.className||existing.className||'',updatedAt:nowIso_()});return'(password existing tidak diubah)';}const salt=Utilities.getUuid();appendObject_('USERS',{userId:input.userId,name:input.name,className:input.className||'',subject:input.subject||'',username:input.username,passwordHash:hashPassword_(input.password,salt),passwordSalt:salt,role:input.role,status:'ACTIVE',createdAt:nowIso_(),updatedAt:nowIso_()});return input.password;}
function migrateLegacyRoles_(){rows_('USERS').filter(u=>String(u.role)==='admin').forEach(u=>updateRowByKey_('USERS','userId',u.userId,{role:'super_admin',updatedAt:nowIso_()}));}
function migrateExamOwners_(fallbackTeacherId){rows_('EXAMS').filter(e=>!e.ownerId).forEach(e=>updateRowByKey_('EXAMS','examId',e.examId,{ownerId:fallbackTeacherId,updatedAt:nowIso_()}));}
function seedDemoExam_(){const examId='EX-DEMO-001',start=new Date(Date.now()-3600000),end=new Date(Date.now()+7*24*3600000);appendObject_('EXAMS',{examId,ownerId:'T-001',title:'Ulangan Harian Fisika',subject:'Fisika',className:'XI IPA 1',startTime:start.toISOString(),endTime:end.toISOString(),durationMinutes:45,questionCount:5,status:'ACTIVE',randomizeQuestion:true,randomizeOption:true,resultVisibility:'immediate',token:'FISIKA26',attemptPolicy:'single',instructions:'Pilih satu jawaban paling tepat. Pastikan seluruh jawaban tersimpan sebelum mengirim ujian.',createdAt:nowIso_(),updatedAt:nowIso_()});const data=[['Besaran yang memiliki satuan SI newton adalah ...','gaya','usaha','daya','tekanan','A'],['Sebuah benda bergerak dengan kecepatan 10 m/s selama 5 s. Jarak yang ditempuh adalah ...','2 m','15 m','50 m','100 m','C'],['Hukum Newton I membahas tentang ...','aksi-reaksi','kelembaman benda','percepatan benda','gravitasi','B'],['Satuan SI untuk energi adalah ...','watt','pascal','joule','newton','C'],['Jika massa benda 2 kg dan percepatannya 3 m/s², gaya resultannya adalah ...','5 N','6 N','8 N','9 N','B']];data.forEach((q,i)=>{const id='Q-DEMO-'+String(i+1).padStart(3,'0');appendObject_('QUESTIONS',{questionId:id,examId,questionText:q[0],optionA:q[1],optionB:q[2],optionC:q[3],optionD:q[4],imageFileId:'',questionType:'MULTIPLE_CHOICE',difficulty:i<2?'Mudah':'Sedang',tag:'Fisika Dasar',status:'ACTIVE',createdAt:nowIso_(),updatedAt:nowIso_()});appendObject_('ANSWER_KEYS',{questionId:id,correctAnswer:q[5],score:20})});}
function randomPassword_(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#';let out='';for(let i=0;i<14;i++)out+=chars[Math.floor(Math.random()*chars.length)];return out;}
function showConfiguration(){const props=PropertiesService.getScriptProperties();return{SPREADSHEET_ID:props.getProperty('SPREADSHEET_ID'),DRIVE_FOLDER_ID:props.getProperty('DRIVE_FOLDER_ID'),PUBLIC_QUESTION_IMAGES:props.getProperty('PUBLIC_QUESTION_IMAGES')}}
function resetSuperAdminPassword(){const admin=rows_('USERS').find(u=>String(u.role)==='super_admin');if(!admin)throw new Error('Super Admin belum ada. Jalankan setupSainsMasemba().');const password=randomPassword_(),salt=Utilities.getUuid();updateRowByKey_('USERS','userId',admin.userId,{passwordHash:hashPassword_(password,salt),passwordSalt:salt,updatedAt:nowIso_()});console.log('Password Super Admin baru: '+password);return password;}
