function setupSainsMasemba(){
  const props=PropertiesService.getScriptProperties();let spreadsheetId=props.getProperty('SPREADSHEET_ID'),ss;if(spreadsheetId){ss=SpreadsheetApp.openById(spreadsheetId)}else{ss=SpreadsheetApp.create('SainsMasemba Database');spreadsheetId=ss.getId();props.setProperty('SPREADSHEET_ID',spreadsheetId)}
  Object.keys(SM.SHEETS).forEach(name=>ensureSheet_(ss,name,SM.SHEETS[name]));let folderId=props.getProperty('DRIVE_FOLDER_ID');if(!folderId){const folder=DriveApp.createFolder('SainsMasemba Question Images');folderId=folder.getId();props.setProperty('DRIVE_FOLDER_ID',folderId)}props.setProperty('PUBLIC_QUESTION_IMAGES','true');getPepper_();migrateLegacyRoles_();
  ensureUser_({userId:'SA-001',name:'Super Admin SainsMasemba',username:'superadmin',email:'admin@sainsmasemba.local',phone:'',className:'',subject:'',role:'super_admin',password:'super123'});
  ensureUser_({userId:'T-001',name:'Guru Fisika SainsMasemba',username:'guru',email:'guru@sainsmasemba.local',phone:'',className:'',subject:'Fisika',role:'teacher',password:'guru123'});
  ensureUser_({userId:'S-001',name:'Siswa Demo',username:'siswa',email:'siswa@sainsmasemba.local',phone:'',className:'XI IPA 1',subject:'',role:'student',password:'siswa123'});
  migrateExamOwners_('T-001');migrateQuestionBank_();if(!findRowByKey_('EXAMS','examId','EX-DEMO-001'))seedDemoExam_();
  const result={spreadsheetId,spreadsheetUrl:ss.getUrl(),driveFolderId:folderId,demoAccounts:{superAdmin:{username:'superadmin',password:'super123'},teacher:{username:'guru',password:'guru123'},student:{username:'siswa',password:'siswa123'}}};console.log(JSON.stringify(result,null,2));return result;
}
function ensureUser_(input){const existing=findRowByKey_('USERS','username',input.username);if(existing){updateRowByKey_('USERS','userId',existing.userId,{email:input.email||existing.email||'',phone:input.phone||existing.phone||'',role:input.role,subject:input.subject||existing.subject||'',className:input.className||existing.className||'',updatedAt:nowIso_()});return'(password existing tidak diubah)';}const salt=Utilities.getUuid();appendObject_('USERS',{userId:input.userId,name:input.name,email:input.email||'',phone:input.phone||'',className:input.className||'',subject:input.subject||'',username:input.username,passwordHash:hashPassword_(input.password,salt),passwordSalt:salt,role:input.role,status:'ACTIVE',createdAt:nowIso_(),updatedAt:nowIso_()});return input.password;}
function migrateLegacyRoles_(){rows_('USERS').filter(u=>String(u.role)==='admin').forEach(u=>updateRowByKey_('USERS','userId',u.userId,{role:'super_admin',updatedAt:nowIso_()}));}
function migrateExamOwners_(fallbackTeacherId){rows_('EXAMS').filter(e=>!e.ownerId).forEach(e=>updateRowByKey_('EXAMS','examId',e.examId,{ownerId:fallbackTeacherId,updatedAt:nowIso_()}));}
function migrateQuestionBank_(){const exams=rows_('EXAMS'),maps=rows_('EXAM_QUESTIONS');rows_('QUESTIONS').forEach((q,index)=>{let authorId=String(q.authorId||'');if(!authorId&&q.examId){const exam=exams.find(e=>String(e.examId)===String(q.examId));authorId=exam?String(exam.ownerId||''):'';}if(!authorId)authorId='T-001';if(String(q.authorId||'')!==authorId)updateRowByKey_('QUESTIONS','questionId',q.questionId,{authorId,updatedAt:nowIso_()});if(q.examId&&!maps.some(m=>String(m.examId)===String(q.examId)&&String(m.questionId)===String(q.questionId))){const order=maps.filter(m=>String(m.examId)===String(q.examId)).length+1;appendObject_('EXAM_QUESTIONS',{examId:String(q.examId),questionId:String(q.questionId),orderNo:order});maps.push({examId:String(q.examId),questionId:String(q.questionId),orderNo:order});}});}
function seedDemoExam_(){const examId='EX-DEMO-001',start=new Date(Date.now()-3600000),end=new Date(Date.now()+7*24*3600000);appendObject_('EXAMS',{examId,ownerId:'T-001',title:'Ulangan Harian Fisika',subject:'Fisika',className:'XI IPA 1',descriptionHtml:'<p>Ulangan harian dengan dukungan <strong>WYSIWYG</strong> dan LaTeX seperti \\(F=ma\\).</p>',startTime:start.toISOString(),endTime:end.toISOString(),durationMinutes:45,questionCount:5,status:'OPEN',randomizeQuestion:true,randomizeOption:true,resultVisibility:'immediate',token:'FISIKA26',attemptPolicy:'single',instructions:'Pastikan seluruh jawaban tersimpan sebelum mengumpulkan.',rulesHtml:'<ol><li>Kerjakan mandiri.</li><li>Dilarang menutup aplikasi sebelum submit berhasil.</li></ol>',createdAt:nowIso_(),updatedAt:nowIso_()});const data=[['Besaran yang memiliki satuan SI newton adalah ...','gaya','usaha','daya','tekanan','A'],['Sebuah benda bergerak dengan kecepatan 10 m/s selama 5 s. Jarak yang ditempuh adalah ...','2 m','15 m','50 m','100 m','C'],['Hukum Newton I membahas tentang ...','aksi-reaksi','kelembaman benda','percepatan benda','gravitasi','B'],['Satuan SI untuk energi adalah ...','watt','pascal','joule','newton','C'],['Jika massa benda 2 kg dan percepatannya 3 m/s², gaya resultannya adalah ...','5 N','6 N','8 N','9 N','B']];data.forEach((q,i)=>{const id='Q-DEMO-'+String(i+1).padStart(3,'0');appendObject_('QUESTIONS',{questionId:id,examId:'',authorId:'T-001',topicCode:'Fisika Dasar',blueprintCode:'',code:'FIS-'+String(i+1).padStart(3,'0'),stimulusOrder:i+1,questionText:q[0],questionHtml:'<p>'+q[0]+'</p>',explanation:'<p>Kunci jawaban: <strong>'+q[5]+'</strong>.</p>',optionA:'<p>'+q[1]+'</p>',optionB:'<p>'+q[2]+'</p>',optionC:'<p>'+q[3]+'</p>',optionD:'<p>'+q[4]+'</p>',optionE:'',imageFileId:'',questionType:'SINGLE_CHOICE',scoringMode:'EXACT_MATCH',maxScore:20,difficulty:i<2?'Mudah':'Sedang',tag:'Fisika Dasar',status:'PUBLISHED',createdAt:nowIso_(),updatedAt:nowIso_()});appendObject_('ANSWER_KEYS',{questionId:id,correctAnswer:q[5],correctAnswers:q[5],score:20,maxScore:20});appendObject_('EXAM_QUESTIONS',{examId,questionId:id,orderNo:i+1})});}
function randomPassword_(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#';let out='';for(let i=0;i<14;i++)out+=chars[Math.floor(Math.random()*chars.length)];return out;}
function showConfiguration(){const props=PropertiesService.getScriptProperties();return{SPREADSHEET_ID:props.getProperty('SPREADSHEET_ID'),DRIVE_FOLDER_ID:props.getProperty('DRIVE_FOLDER_ID'),PUBLIC_QUESTION_IMAGES:props.getProperty('PUBLIC_QUESTION_IMAGES')}}
function resetSuperAdminPassword(){const admin=rows_('USERS').find(u=>String(u.role)==='super_admin');if(!admin)throw new Error('Super Admin belum ada. Jalankan setupSainsMasemba().');const password=randomPassword_(),salt=Utilities.getUuid();updateRowByKey_('USERS','userId',admin.userId,{passwordHash:hashPassword_(password,salt),passwordSalt:salt,updatedAt:nowIso_()});console.log('Password Super Admin baru: '+password);return password;}
